<div id='menu'>
	<div id="tierPm" onmouseover="ShowSub(this)" onmouseout="CloseSub(this)">
		PROGRAMING MODE
<div id="tierPm2"><?php
echo "<table align='center' width='900' id='tables_css2' bgcolor='#cfcfcf'>";
	echo "<tr>";
		echo "<td>";
			echo "<input type=submit value='apl' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type=submit value='asterisk' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='clike' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='clojure' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='cobol' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='coffeescript' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='commonlisp' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='css' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='cypher' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='d' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='diff' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='django' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='dtd' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='dylan' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='ecl' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='eiffel' onclick='change()' name='mode'>";
		echo "</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td>";
			echo "<input type='submit' value='erlang' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='fortran' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='gas' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='gfm' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='gherkin' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='go' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='groovy' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='haml' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='haskell' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='haxe' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='htmlembedded' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='htmlmixed' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='http' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='jade' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='javascript' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='jinja2' onclick='change()' name='mode'>";
		echo "</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td>";
			echo "<input type='submit' value='julia' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='livescript' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='lua' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='markdown' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='mirc' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='mllike' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='nginx' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='ntriples' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='octave' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='pascal' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='pegjs' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='perl' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='php' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='pig' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='properties' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='puppet' onclick='change()' name='mode'>";
		echo "</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td>";
			echo "<input type='submit' value='python' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='q' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='r' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='rpm' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='rst' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='ruby' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='rust' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='sass' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='scheme' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='shell' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='sieve' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='smalltalk' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='smarty' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='smartymixed' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='solr' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='sparql' onclick='change()' name='mode'>";
		echo "</td>";
	echo "</tr>";
	echo "<tr>";
		echo "<td>";
			echo "<input type='submit' value='sql' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='stex' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='tcl' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='tiddlywiki' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='tiki' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='toml' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='turtle' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='vb' onclick='change()' name='mode'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='vbscript' onclick='change()' name='mode' title='Z80'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='velocity' onclick='change()' name='mode' title='Z80'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='verilog' onclick='change()' name='mode' title='Z80'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='xml' onclick='change()' name='mode' title='Z80'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='xquery' onclick='change()' name='mode' title='Z80'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='yaml' onclick='change()' name='mode' title='Z80'>";
		echo "</td>";
		echo "<td>";
			echo "<input type='submit' value='z80' onclick='change()' name='mode' title='Z80'>";
		echo "</td>";
		echo "<td>";
		echo "</td>";
	echo "</tr>";
echo "</table>";
?>
</div></div></div>