<?php
	$defualt_text_x = "";
	$defualt_text_x .= "\n";
	$defualt_text_x .= $defualt_text_pre;	
	$defualt_text_x .= "\n";
	
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= " if(".$reque."=='' || ".$reque."=='view')";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t{";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//START YOUR CODE BELOW THIS LINE";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= $defualt_text_view;
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//END YOUR CODE ABOVE THIS LINE";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t";
	$defualt_text_x .= "\t}\n";	
	
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "elseif(".$reque."=='add')";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t{";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//START YOUR CODE BELOW THIS LINE";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= $defualt_text_add;
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//END YOUR CODE ABOVE THIS LINE";
	$defualt_text_x .= "\n\t\t}\n";
		
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "elseif(".$reque."=='edit')";
	$defualt_text_x .= "\n\t\t{";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//START YOUR CODE BELOW THIS LINE";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= $defualt_text_edit;
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//END YOUR CODE ABOVE THIS LINE";
	$defualt_text_x .= "\n\t\t}\n";	
	
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "elseif(".$reque."=='list')";
	$defualt_text_x .= "\n\t\t{";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//START YOUR CODE BELOW THIS LINE";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= $defualt_text_list;
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//END YOUR CODE ABOVE THIS LINE";
	$defualt_text_x .= "\n\t\t}\n";
		
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "elseif(".$reque."=='delete')";
	$defualt_text_x .= "\n\t\t{";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//START YOUR CODE BELOW THIS LINE";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= $defualt_text_delete;
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//END YOUR CODE ABOVE THIS LINE";
	$defualt_text_x .= "\n\t\t}\n";	
	
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "elseif(".$reque."=='setup')";
	$defualt_text_x .= "\n\t\t{";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//START YOUR CODE BELOW THIS LINE";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= $defualt_text_setup;
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "\n";
	$defualt_text_x .= "\t\t";
	$defualt_text_x .= "//END YOUR CODE ABOVE THIS LINE";
	$defualt_text_x .= "\n\t\t}\n";
	
	$precode = $defualt_text_x;
	?>