<?php 

 if(@privacy('Free|Open')=='Granted')
{
//START YOUR CODE (ANY CODE THAT SHOULD BE EXCECUTED ABOVE THE SUBSEQUENT PAGES) BELOW THIS LINE



//END YOUR CODE (ANY CODE THAT SHOULD BE EXCECUTED ABOVE THE SUBSEQUENT PAGES) ABOVE THIS LINE


subPages($_REQUEST["ref"],$_REQUEST["segment"]);

//START YOUR CODE (ANY CODE THAT SHOULD BE EXCECUTED BELOW THE SUBSEQUENT PAGES) BELOW THIS LINE



//END YOUR CODE (ANY CODE THAT SHOULD BE EXCECUTED BELOW THE SUBSEQUENT PAGES) ABOVE THIS LINE

}
 
?>